/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package openpkm.core.raindrop;

import java.awt.Component;
import java.io.IOException;
import java.util.Set;
import java.util.TreeSet;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.swing.SwingConstants;
import openpkm.raindrop.RaindropChildrenCollection;
import openpkm.raindrop.RaindropCollection;
import openpkm.utils.Utils;
import org.openide.util.ImageUtilities;

/**
 *
 * @author rok
 */
public class TopicRaindropVisualPanel1 extends javax.swing.JPanel 
{
    private static final Logger LOG = Logger.getLogger(TopicRaindropVisualPanel1.class.getName());
    
    private final DefaultComboBoxModel<RaindropChildrenCollection> model = new DefaultComboBoxModel<>();
    private final ListCellRenderer renderer = new ListCellRendererImpl();       
    
    /**
     * Creates new form TopicRaindropVisualPanel1
     */
    public TopicRaindropVisualPanel1() 
    {
        initComponents();
    }
    
    @Override
    public String getName() 
    {
        return "General";
    }    
    
    public RaindropCollection getRaindropCollection()
    {
        return (RaindropCollection)model.getSelectedItem();
    }
    
    public void setRaindropCollection(RaindropCollection collection)
    {
        model.setSelectedItem(collection);
    }  
    
    public String getTopicTag()
    {
        return jTextField1.getText().trim();
    }      
    
    public void setRaindrop(RaindropCollection collection)
    {
        Set<RaindropChildrenCollection> collections = new TreeSet<RaindropChildrenCollection>(RaindropCollection.titleComparator());
        model.removeAllElements();
        try
        {
            collections.addAll(collection.getAccount().getChildrenCollections(collection.getCollectionID()));
            model.addAll(collections);              
        }
        catch(IOException e)
        {
            LOG.warning(e.getMessage());
        }
    }  
    
    private static class ListCellRendererImpl extends JLabel implements ListCellRenderer<RaindropChildrenCollection>
    {
        public ListCellRendererImpl() 
        {
            setOpaque(true);
            setHorizontalAlignment(SwingConstants.LEADING);
            setVerticalAlignment(CENTER);
        }   

        @Override
        public Component getListCellRendererComponent(JList list, RaindropChildrenCollection collection, int index, boolean isSelected, boolean cellHasFocus) 
        {
            if (isSelected) {
                setBackground(list.getSelectionBackground());
                setForeground(list.getSelectionForeground());
            } else {
                setBackground(list.getBackground());
                setForeground(list.getForeground());
            }

            if(collection == null)
            {
                setText("");
                setIcon(null);
            }
            else
            {
                try
                {
                    setIcon(ImageUtilities.image2Icon(Utils.resizeImage(collection.getImage(), 16, 16)));                    
                }
                catch(IOException e)
                {
                    LOG.warning(e.getMessage());
                }
                setText(collection.getTitle());                   
            }
            
            return this;
        }
    }     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(TopicRaindropVisualPanel1.class, "TopicRaindropVisualPanel1.jLabel1.text") + ":"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(jLabel1, gridBagConstraints);

        jComboBox1.setModel(model);
        jComboBox1.setRenderer(renderer);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jComboBox1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        add(filler1, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(TopicRaindropVisualPanel1.class, "TopicRaindropVisualPanel1.jLabel2.text") + ":"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(jLabel2, gridBagConstraints);

        jTextField1.setColumns(18);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jTextField1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JComboBox<RaindropChildrenCollection> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
