package openpkm.asciidoc;

/* Generated By:JavaCC: Do not edit this line. AsciiDocParserConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AsciiDocParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int HEADER1 = 1;
  /** RegularExpression Id. */
  int HEADER2 = 2;
  /** RegularExpression Id. */
  int HEADER3 = 3;
  /** RegularExpression Id. */
  int BOLD = 4;
  /** RegularExpression Id. */
  int ITALIC = 5;
  /** RegularExpression Id. */
  int LIST_ITEM = 6;
  /** RegularExpression Id. */
  int NEWLINE = 7;
  /** RegularExpression Id. */
  int WHITESPACE = 8;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 9;
  /** RegularExpression Id. */
  int HEX_LITERAL = 10;
  /** RegularExpression Id. */
  int HEX_DIGIT = 11;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 12;
  /** RegularExpression Id. */
  int REAL_LITERAL = 13;
  /** RegularExpression Id. */
  int EXPONENT = 14;
  /** RegularExpression Id. */
  int SIMPLE_STRING_LITERAL = 15;
  /** RegularExpression Id. */
  int ESCAPED_CHAR = 16;
  /** RegularExpression Id. */
  int PRINT_CHAR = 17;
  /** RegularExpression Id. */
  int ENCODED_STRING_LITERAL = 18;
  /** RegularExpression Id. */
  int BINARY_LITERAL = 19;
  /** RegularExpression Id. */
  int OCTET = 20;
  /** RegularExpression Id. */
  int ENCODED_CHARACTER = 21;
  /** RegularExpression Id. */
  int SIMPLE_ID = 22;
  /** RegularExpression Id. */
  int LETTER = 23;
  /** RegularExpression Id. */
  int DIGIT = 24;
  /** RegularExpression Id. */
  int LPAREN = 25;
  /** RegularExpression Id. */
  int RPAREN = 26;
  /** RegularExpression Id. */
  int LBRACE = 27;
  /** RegularExpression Id. */
  int RBRACE = 28;
  /** RegularExpression Id. */
  int LBRACKET = 29;
  /** RegularExpression Id. */
  int RBRACKET = 30;
  /** RegularExpression Id. */
  int SEMICOLON = 31;
  /** RegularExpression Id. */
  int COLON = 32;
  /** RegularExpression Id. */
  int COMMA = 33;
  /** RegularExpression Id. */
  int DOT = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<HEADER1>",
    "<HEADER2>",
    "<HEADER3>",
    "<BOLD>",
    "<ITALIC>",
    "<LIST_ITEM>",
    "<NEWLINE>",
    "<WHITESPACE>",
    "<INTEGER_LITERAL>",
    "<HEX_LITERAL>",
    "<HEX_DIGIT>",
    "<OCTAL_LITERAL>",
    "<REAL_LITERAL>",
    "<EXPONENT>",
    "<SIMPLE_STRING_LITERAL>",
    "<ESCAPED_CHAR>",
    "<PRINT_CHAR>",
    "<ENCODED_STRING_LITERAL>",
    "<BINARY_LITERAL>",
    "<OCTET>",
    "<ENCODED_CHARACTER>",
    "<SIMPLE_ID>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "\".\"",
  };

}
