/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/templateDataObjectMultiForm.java to edit this template
 */
package openpkm.markdown;

import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JToolBar;
import openpkm.base.HtmlFilesProvider;
import org.netbeans.api.project.FileOwnerQuery;
import org.netbeans.api.project.Project;
import org.netbeans.core.spi.multiview.CloseOperationState;
import org.netbeans.core.spi.multiview.MultiViewElement;
import org.netbeans.core.spi.multiview.MultiViewElementCallback;
import org.openide.awt.UndoRedo;
import org.openide.filesystems.FileObject;
import org.openide.util.Lookup;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

@MultiViewElement.Registration(
        displayName = "#LBL_Markdown_VISUAL",
        iconBase = "openpkm/markdown/resources/markdown.png",
        mimeType = "text/x-markdown",
        persistenceType = TopComponent.PERSISTENCE_NEVER,
        preferredID = "MarkdownVisual",
        position = 2000
)
@Messages("LBL_Markdown_VISUAL=Visual")
public final class MarkdownVisualElement extends JFXPanel implements MultiViewElement
{
    private final Lookup context;     
    
    private WebView browser;
    private JToolBar toolbar = new JToolBar();
    private transient MultiViewElementCallback callback;

    public MarkdownVisualElement(Lookup context) 
    {
        this.context = context;
        initComponents();
    }

    @Override
    public String getName() 
    {
        return "MarkdownVisualElement";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public JComponent getVisualRepresentation() 
    {
        return this;
    }

    @Override
    public JComponent getToolbarRepresentation() 
    {
        return toolbar;
    }

    @Override
    public Action[] getActions() {
        return new Action[0];
    }

    @Override
    public Lookup getLookup() 
    {
        return context;
    }

    @Override
    public void componentOpened() 
    {
        if(browser ==  null)
        {
            Platform.runLater(new Runnable() {
                @Override
                public void run() 
                {
                    browser = new WebView();
                    Scene scene = new Scene(browser);
                    /*
                    if (isDarkLaF)
                    {
                        scene.getStylesheets().add(getClass().getResource("/openpkm/asciidoc/resources/javafx-nb-dark.css").toString());
                        // Loading default content to force apply a content with css for dark background
                        //browser.getEngine().loadContent(readLoadingPage());
                    }              
                    */
                    setScene(scene);                    
                }
            });            
        }
    }

    @Override
    public void componentClosed() {
    }

    @Override
    public void componentShowing() {
    }

    @Override
    public void componentHidden() {
    }

    @Override
    public void componentActivated() 
    {  
        MarkdownDataObject data = context.lookup(MarkdownDataObject.class);        
        Project project = FileOwnerQuery.getOwner(data.getPrimaryFile());        
        HtmlFilesProvider provider = project.getLookup().lookup(HtmlFilesProvider.class);             
        if(provider != null)
        {
            FileObject file = provider.getDataFile(data.getPrimaryFile().getName());
            if(file != null)
            {
                final String urlFile = file.toURI().toString();
                //final String urlTheme = theme.getUrl();
                Platform.runLater(new Runnable() {
                    @Override
                    public void run() 
                    {
                        WebEngine webEngine = browser.getEngine();
                        //webEngine.setUserStyleSheetLocation(urlTheme);
                        webEngine.load(urlFile);  
                    }
                });
            }             
        }              
    }

    @Override
    public void componentDeactivated()
    {
    }

    @Override
    public UndoRedo getUndoRedo() 
    {
        return UndoRedo.NONE;
    }

    @Override
    public void setMultiViewCallback(MultiViewElementCallback callback) 
    {
        this.callback = callback;
    }

    @Override
    public CloseOperationState canCloseElement() 
    {
        return CloseOperationState.STATE_OK;
    }
}
