/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package openpkm.utils;

import openpkm.base.DisplayNameProvider;
import openpkm.base.Source;
import openpkm.base.TitleProvider;
import org.cef.browser.CefBrowser;

/**
 *
 * @author Rok Koren
 */
public class SourceVisualPanel extends javax.swing.JPanel 
{ 
    private final Source source;
    
    /**
     * Creates new form WatchLaterVisualPanel
     */
    public SourceVisualPanel(Source source, CefBrowser browser) 
    {
        this.source = source;
        initComponents(); 
        add(browser.getUIComponent());        
    }
    
    @Override
    public String getName() 
    {
        if(source instanceof TitleProvider provider)
        {
            return provider.getTitle();            
        }
        DisplayNameProvider provider = source.getLookup().lookup(DisplayNameProvider.class);
        return provider.getDisplayName(DisplayNameProvider.TextFormat.PLAIN);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
