/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/templateTopComponent637.java to edit this template
 */
package openpkm.core;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.SortedSet;
import java.util.TreeSet;
import java.util.logging.Logger;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import openpkm.base.ChangeSupportProvider;
import openpkm.base.DataGroupProvider;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.awt.UndoRedo;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.loaders.DataObject;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Children;
import org.openide.nodes.FilterNode;
import org.openide.nodes.Node;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.Utilities;
import org.openide.util.lookup.Lookups;
import org.openide.util.lookup.ProxyLookup;
import openpkm.base.DataProvider;
import openpkm.base.FilterTagsProvider;
import openpkm.base.GoalsGraphProvider;
import openpkm.base.GoalsProvider;
import openpkm.base.KnowledgeGraphProvider;
import openpkm.base.Source;
import openpkm.base.SourceProviderWrapper;
import openpkm.base.TagsProvider;
import openpkm.base.TopicsProvider;
import org.openide.filesystems.FileObject;
import org.openide.loaders.DataFolder;
import org.openide.loaders.DataObjectNotFoundException;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//openpkm.core//Bookshelf//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "BookshelfTopComponent",
        iconBase = "openpkm/core/resources/bookshelf.png",
        persistenceType = TopComponent.PERSISTENCE_ONLY_OPENED
)
@TopComponent.Registration(mode = "properties", openAtStartup = true)
@ActionID(category = "Window", id = "openpkm.core.BookshelfTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_BookshelfAction",
        preferredID = "BookshelfTopComponent"
)
@Messages({
    "CTL_BookshelfAction=Bookshelf",
    "CTL_BookshelfTopComponent=Bookshelf Window",
    "HINT_BookshelfTopComponent=This is a Bookshelf window"
})
public final class BookshelfTopComponent extends TopComponent implements ExplorerManager.Provider
{
    private static final Logger LOG = Logger.getLogger(BookshelfTopComponent.class.getName()); 
    
    private final ExplorerManager explorerManager = new ExplorerManager();
    private final UndoRedo.Manager undoRedoManager = new UndoRedo.Manager();  
    private final DataObjects dataObjects = new DataObjects();

    private Lookup.Result<DataProvider> result;      
    
    public BookshelfTopComponent() 
    {
        initComponents();
        setName(Bundle.CTL_BookshelfTopComponent());
        setToolTipText(Bundle.HINT_BookshelfTopComponent());
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
        //putClientProperty(TopComponent.PROP_DRAGGING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_MAXIMIZATION_DISABLED, Boolean.TRUE);
        associateLookup(new ProxyLookup(ExplorerUtils.createLookup(explorerManager, getActionMap()), Lookups.singleton(this)));  
        explorerManager.setRootContext(new AbstractNode(dataObjects));   
        result = Utilities.actionsGlobalContext().lookupResult(DataProvider.class);          
    }
    
    @Override
    public ExplorerManager getExplorerManager() 
    {
        return explorerManager;
    }
    
    @Override
    public UndoRedo getUndoRedo() 
    {
        return undoRedoManager;
    }     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listView1 = new org.openide.explorer.view.ListView();

        setLayout(new java.awt.BorderLayout());

        listView1.setDragSource(true);
        add(listView1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openide.explorer.view.ListView listView1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
        result.addLookupListener(dataObjects);  
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
        result.removeLookupListener(dataObjects); 
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
    
    private final class DataObjects extends Children.Keys<DataObject> implements LookupListener, ChangeListener
    {
        private final FilterTagsProvider filterTags;
        
        private final List<DataProvider> providers = new ArrayList();     

        public DataObjects() 
        {
            filterTags = Lookup.getDefault().lookup(FilterTagsProvider.class);
            if(filterTags != null) 
            {
                filterTags.addChangeListener(this);
            }             
        }                
                        
        @Override
        public void resultChanged(LookupEvent event) 
        { 
            Collection<DataProvider> coll = (Collection<DataProvider>) result.allInstances();
            if(!coll.isEmpty())
            {                                
                for(DataProvider provider : providers)
                {
                    provider.removeChangeListener(this);
                    
                    KnowledgeGraphProvider topicProvider = provider.getProvider().getLookup().lookup(KnowledgeGraphProvider.class);
                    if(topicProvider instanceof ChangeSupportProvider csp)
                    {
                        csp.removeChangeListener(this);
                    }  
                    
                    GoalsGraphProvider goalProvider = provider.getProvider().getLookup().lookup(GoalsGraphProvider.class);
                    if(goalProvider instanceof ChangeSupportProvider csp)
                    {
                        csp.removeChangeListener(this);
                    }                     
                }
                
                providers.clear();
                for(DataProvider provider : coll)
                {
                    provider.addChangeListener(this);
                    
                    KnowledgeGraphProvider topicProvider = provider.getProvider().getLookup().lookup(KnowledgeGraphProvider.class);
                    if(topicProvider instanceof ChangeSupportProvider csp)
                    {
                        csp.addChangeListener(this);
                    }                      
                    
                    GoalsGraphProvider goalProvider = provider.getProvider().getLookup().lookup(GoalsGraphProvider.class);
                    if(goalProvider instanceof ChangeSupportProvider csp)
                    {
                        csp.addChangeListener(this);
                    }                     
                }                
                providers.addAll(coll);
                updateKeys();                
            }
        }           
        
        @Override
        protected void addNotify() 
        {
            updateKeys();
        }
        
        public Collection<DataProvider> getProviders()
        {
            if(providers != null)
            {
                return Collections.unmodifiableCollection(providers);
            }
            return Collections.EMPTY_LIST;
        }

        private void updateKeys() 
        {                         
            SortedSet<DataObject> sorted = new TreeSet<DataObject>(DataGroupProvider.displayNameComparator());            
            for(DataProvider provider : getProviders())
            {                                
                try
                {
                    for(FileObject file : provider.getFiles())
                    {
                        DataObject data = null;
                        if(file.isData())
                        {
                            try
                            {
                                data = DataObject.find(file);                    
                            }
                            catch(DataObjectNotFoundException e)
                            {
                                LOG.warning(e.getMessage());
                            }
                        }
                        else if(file.isFolder())
                        {
                            data = DataFolder.findFolder(file);
                        }                     

                        if(provider.contains(data))
                        {                        
                            boolean isTag = true;
                            boolean isTopic = true;
                            boolean isGoal = true;

                            if(filterTags != null)
                            {
                                TagsProvider tagsProvider = data.getLookup().lookup(TagsProvider.class);
                                if(tagsProvider != null)
                                {
                                    isTag = filterTags.isTag(tagsProvider);
                                }                            
                            }

                            KnowledgeGraphProvider topicProvider = provider.getProvider().getLookup().lookup(KnowledgeGraphProvider.class);
                            if(topicProvider != null)
                            {
                                SourceProviderWrapper sourceProvider = data.getLookup().lookup(SourceProviderWrapper.class);
                                if(sourceProvider != null)
                                {
                                    Source source = sourceProvider.getSource();
                                    if(source != null)
                                    {
                                        TopicsProvider topicsProvider = source.getLookup().lookup(TopicsProvider.class);
                                        if(topicsProvider != null)
                                        {
                                            isTopic = topicProvider.isTopic(topicsProvider);
                                        }                                                 
                                    }            
                                }                                                                                    
                            }

                            GoalsGraphProvider goalProvider = provider.getProvider().getLookup().lookup(GoalsGraphProvider.class);
                            if(goalProvider != null)
                            {
                                SourceProviderWrapper sourceProvider = data.getLookup().lookup(SourceProviderWrapper.class);
                                if(sourceProvider != null)
                                {
                                    Source source = sourceProvider.getSource();
                                    if(source != null)
                                    {
                                        GoalsProvider goalsProvider = source.getLookup().lookup(GoalsProvider.class);
                                        if(goalsProvider != null)
                                        {
                                            isGoal = goalProvider.isGoal(goalsProvider);
                                        }                                                 
                                    }            
                                }                                                                                    
                            }                        

                            if(isTag && isTopic && isGoal)                    
                            {
                                sorted.add(data);                  
                            }                        
                        }
                    } 
                }
                catch(IOException e)
                {
                    LOG.warning(e.getMessage());
                }  
            }             
            
            setKeys(sorted); 
            
            /*
            SwingUtilities.invokeLater(() -> 
            {
                SortedSet<OpenPkmDataObject> data = new TreeSet<OpenPkmDataObject>(OpenPkmData.titleComparator());
                data.addAll(getData(provider));     
                setKeys(data);    
            });
            */            
        }

        @Override
        protected void removeNotify()
        {
            setKeys(Collections.<DataObject>emptySet());
        }

        @Override
        protected Node[] createNodes(DataObject data) 
        {
            return new Node[] {new FilterNode(data.getNodeDelegate())};
        } 

        @Override
        public void stateChanged(ChangeEvent e) 
        {
            updateKeys();
        }         
    }    
}
