/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/templateTopComponent637.java to edit this template
 */
package openpkm.core;

import java.awt.BorderLayout;
import java.util.logging.Logger;
import openpkm.jcef.CefClientProvider;
import org.cef.browser.CefBrowser;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//openpkm.core//Facebook//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "FacebookTopComponent",
        iconBase = "openpkm/core/resources/facebook.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "openpkm.core.FacebookTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_FacebookWindowAction",
        preferredID = "FacebookTopComponent"
)
@Messages({
    "CTL_FacebookWindowAction=Facebook",
    "CTL_FacebookTopComponent=Facebook Window",
    "HINT_FacebookTopComponent=This is a Facebook window"
})
public final class FacebookTopComponent extends TopComponent 
{
    public static final String FACEBOOK_URL = "https://facebook.com";
    
    private static final Logger LOG = Logger.getLogger(FacebookTopComponent.class.getName());     
    
    private CefBrowser browser; 
    
    public FacebookTopComponent() 
    {
        initComponents();
        setName(Bundle.CTL_FacebookTopComponent());
        setToolTipText(Bundle.HINT_FacebookTopComponent());
        
        CefClientProvider provider = Lookup.getDefault().lookup(CefClientProvider.class);
        if(provider != null)
        {
            try
            {
                browser = provider.getCefClient().createBrowser(FACEBOOK_URL, false, false);  
                add(browser.getUIComponent(), BorderLayout.CENTER);
            }
            catch(Exception e)
            {
                LOG.warning(e.getMessage());
            }
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened()
    {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() 
    {
        // TODO add custom code on component closing
        if(browser != null)
        {
            browser.close(false);
        }        
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
