/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/templateTopComponent637.java to edit this template
 */
package openpkm.core;

import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.ActionEvent;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.event.ChangeListener;
import javax.swing.undo.CannotRedoException;
import javax.swing.undo.CannotUndoException;
import openpkm.base.HomeProvider;
import openpkm.base.LinkProvider;
import openpkm.jcef.CefAppProvider;
import org.cef.CefClient;
import org.cef.browser.CefBrowser;
import org.cef.browser.CefFrame;
import org.cef.handler.CefLoadHandler;
import org.cef.network.CefRequest;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.actions.CopyAction;
import org.openide.awt.StatusDisplayer;
import org.openide.awt.UndoRedo;
import org.openide.util.ChangeSupport;
import org.openide.util.Lookup;
import org.openide.util.actions.SystemAction;
import org.openide.util.lookup.Lookups;
import org.openide.util.lookup.ProxyLookup;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//openpkm.core//Google//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "GoogleTopComponent",
        iconBase = "openpkm/core/resources/google.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
public final class GoogleTopComponent extends TopComponent implements HomeProvider, LinkProvider, CefLoadHandler
{
    public static final String GOOGLE_URL = "https://www.google.com";
    
    private static final Logger LOG = Logger.getLogger(GoogleTopComponent.class.getName());     
    
    private CefClient client;
    private CefBrowser browser; 
    private BrowserUndoRedo undoRedo;
    
    private final ChangeSupport changeSupport = new ChangeSupport(this);
    
    public GoogleTopComponent() 
    {
        initComponents();
        setName("Google Window");
        setToolTipText("This is a Google window");

        CefAppProvider provider = Lookup.getDefault().lookup(CefAppProvider.class);
        if(provider != null)
        {
            try
            {
                client = provider.getApp().createClient();
                browser = client.createBrowser(GOOGLE_URL, false, false);  
                undoRedo = new BrowserUndoRedo();                
                add(browser.getUIComponent(), BorderLayout.CENTER);                                
            }
            catch(Exception e)
            {
                LOG.warning(e.getMessage());
            }
        } 

        CopyAction copyAction = SystemAction.get(CopyAction.class);
        getActionMap().put(copyAction.getActionMapKey(), copyLinkAction);      
    }
    
    @Override
    public Lookup getLookup() 
    {
        return new ProxyLookup(super.getLookup(), Lookups.singleton(this));
    } 
    
    @Override
    public UndoRedo getUndoRedo()
    {
        return undoRedo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() 
    {
        client.addLoadHandler(this);
    }

    @Override
    public void componentClosed() 
    {
        client.removeLoadHandler();
        if(browser != null)
        {
            browser.close(false);
        } 
        client.dispose();
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
    
    @Override
    public void reloadHome() 
    {
        browser.loadURL(GOOGLE_URL);
    }     
    
    @Override
    public String getLink() 
    {
        return browser.getURL();
    }  

    @Override
    public void onLoadingStateChange(CefBrowser cb, boolean bln, boolean bln1, boolean bln2) 
    {
        changeSupport.fireChange();        
    }

    @Override
    public void onLoadStart(CefBrowser cb, CefFrame cf, CefRequest.TransitionType tt) 
    {
        
    }

    @Override
    public void onLoadEnd(CefBrowser cb, CefFrame cf, int i) 
    {
        changeSupport.fireChange(); 
    }

    @Override
    public void onLoadError(CefBrowser cb, CefFrame cf, ErrorCode ec, String string, String string1) 
    {
    }

    private class BrowserUndoRedo implements UndoRedo 
    {       
        @Override
        public boolean canUndo() {
            return browser.canGoBack();
        }

        @Override
        public void undo() throws CannotUndoException {
            browser.goBack();
        }

        @Override
        public boolean canRedo() {
            return browser.canGoForward();
        }

        @Override
        public void redo() throws CannotRedoException {
            browser.goForward();
        }

        @Override
        public void addChangeListener(ChangeListener cl) 
        {
            changeSupport.addChangeListener(cl);
        }

        @Override
        public void removeChangeListener(ChangeListener cl) {
            changeSupport.removeChangeListener(cl);
        }

        @Override
        public String getUndoPresentationName() 
        {
            return "Back";
        }

        @Override
        public String getRedoPresentationName() 
        {
            return "Forward";
        }
    }   
    
    private final Action copyLinkAction = new AbstractAction() 
    {                
        @Override
        public void actionPerformed(ActionEvent e) 
        {
            String url = getLink();
            if (url != null) 
            {
                Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
                clipboard.setContents(new StringSelection(url),null);
                StatusDisplayer.getDefault().setStatusText("Link copied from " + getName());
            }
        }
    };   
}
