/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/templateTopComponent637.java to edit this template
 */
package openpkm.core;

import java.awt.BorderLayout;
import java.util.logging.Logger;
import openpkm.jcef.CefClientProvider;
import org.cef.browser.CefBrowser;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.util.Lookup;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//openpkm.core//Google//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "GoogleTopComponent",
        iconBase = "openpkm/core/resources/google.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
public final class GoogleTopComponent extends TopComponent 
{
    public static final String GOOGLE_URL = "https://www.google.com";
    
    private static final Logger LOG = Logger.getLogger(GoogleTopComponent.class.getName());     
    
    private CefBrowser browser; 
    
    public GoogleTopComponent() 
    {
        initComponents();
        setName("Google Window");
        setToolTipText("This is a Google window");

        CefClientProvider provider = Lookup.getDefault().lookup(CefClientProvider.class);
        if(provider != null)
        {
            try
            {
                browser = provider.getCefClient().createBrowser(GOOGLE_URL, false, false);  
                add(browser.getUIComponent(), BorderLayout.CENTER);
            }
            catch(Exception e)
            {
                LOG.warning(e.getMessage());
            }
        }         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() 
    {
        // TODO add custom code on component closing
        if(browser != null)
        {
            browser.close(false);
        }          
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
