/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package openpkm.core;

import java.awt.EventQueue;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.SortedSet;
import java.util.TreeSet;
import openpkm.base.KnowledgeGraphProvider;
import openpkm.base.Topic;
import openpkm.utils.TopicNode;
import org.openide.explorer.ExplorerManager;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Children;
import org.openide.nodes.Node;
import org.openide.util.Lookup;

/**
 *
 * @author Rok Koren
 */
public class HomePageVisualPanel1 extends javax.swing.JPanel implements ExplorerManager.Provider
{  
    private final ExplorerManager explorerManager = new ExplorerManager();    
    
    /**
     * Creates new form HomePageVisualPanel1
     */
    public HomePageVisualPanel1() 
    {
        initComponents();
    } 
    
    @Override
    public String getName() 
    {
        return "URL";
    }  
    
    public String getHomePageUrl()
    {
        return jTextField1.getText().trim();
    }
    
    public List<Topic> getHomePageTopics()
    {
        Node[] nodes = explorerManager.getSelectedNodes();
        if(nodes.length > 0)
        {
            List<Topic> topics = new ArrayList<>();
            for(Node node : nodes)
            {
                Topic topic = node.getLookup().lookup(Topic.class);
                if(topic != null)
                {
                    topics.add(topic);
                }
            }
            return topics;
        }
        return null;
    } 
    
    @Override
    public ExplorerManager getExplorerManager() 
    {
        return explorerManager;
    } 
    
    public void setTopics(Lookup.Provider provider)
    {
        assert provider != null;        
        KnowledgeGraphProvider knowledgeGraph = provider.getLookup().lookup(KnowledgeGraphProvider.class);
        if(knowledgeGraph != null)
        {
            TopicsChildren topics = new TopicsChildren(knowledgeGraph);
            explorerManager.setRootContext(new AbstractNode(topics));
        }        
    }     
    
    static final class TopicsChildren extends Children.Keys<Topic> 
    {
        private final KnowledgeGraphProvider provider;

        public TopicsChildren(KnowledgeGraphProvider provider)
        {
            this.provider = provider;
        }  

        @Override
        protected void addNotify() 
        {
            updateKeys();                             
        }

        private void updateKeys() 
        {
            EventQueue.invokeLater(new Runnable() 
            {
                public void run()
                {                                                
                    SortedSet<Topic> topics = new TreeSet<Topic>(Topic.nameComparator());
                    topics.addAll(provider.getRootTopics());           
                    setKeys(topics);                   
                }
            });
        }        

        @Override
        protected void removeNotify() 
        {                            
            setKeys(Collections.<Topic>emptySet());
        }

        @Override
        protected Node[] createNodes(Topic topic) 
        {
            return new Node[] {new TopicNode(provider, topic)};
        }           
    }     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        jLabel2 = new javax.swing.JLabel();
        iconView1 = new org.openide.explorer.view.IconView();

        setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(HomePageVisualPanel1.class, "HomePageVisualPanel1.jLabel1.text") + ":"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(jLabel1, gridBagConstraints);

        jTextField1.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jTextField1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        add(filler1, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(HomePageVisualPanel1.class, "HomePageVisualPanel1.jLabel2.text") + ":"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(iconView1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private org.openide.explorer.view.IconView iconView1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
