/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/template_mypluginPanel.java to edit this template
 */
package openpkm.core;

import java.awt.Dimension;
import java.awt.GridBagConstraints;
import javax.swing.Box.Filler;
import javax.swing.JLabel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import openpkm.base.PasswordProvider;
import org.openide.util.Lookup;

final class SecurityPrivacyPanel extends javax.swing.JPanel implements ChangeListener
{
    private final SecurityPrivacyOptionsPanelController controller;

    SecurityPrivacyPanel(SecurityPrivacyOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
        int gridy = 0;
        for(PasswordProvider provider : Lookup.getDefault().lookupAll(PasswordProvider.class))
        {
            JLabel label = new JLabel(provider.getDisplayName() + ":");
            Filler filler1 = new Filler(new Dimension(0, 10), new Dimension(0, 10), new Dimension(32767, 10));
            
            GridBagConstraints gridBagConstraints1 = new GridBagConstraints();
            gridBagConstraints1.gridx = 0;
            gridBagConstraints1.gridy = gridy;
            gridBagConstraints1.fill = java.awt.GridBagConstraints.VERTICAL;
            gridBagConstraints1.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
            gridBagConstraints1.insets = new java.awt.Insets(0, 5, 0, 5);
            add(label, gridBagConstraints1);
                        
            GridBagConstraints gridBagConstraints2 = new java.awt.GridBagConstraints();
            gridBagConstraints2.gridx = 1;
            gridBagConstraints2.gridy = gridy;
            gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
            add(provider.getField(), gridBagConstraints2);
            
            gridy++;
            
            GridBagConstraints gridBagConstraints3 = new java.awt.GridBagConstraints();
            gridBagConstraints3.gridx = 0;
            gridBagConstraints3.gridy = gridy;
            gridBagConstraints3.gridwidth = 2;
            gridBagConstraints3.fill = java.awt.GridBagConstraints.VERTICAL;
            add(filler1, gridBagConstraints3); 
            
            provider.addListener(this);
            
            gridy++;
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents

    void load() {
        // TODO read settings and initialize GUI
        // Example:        
        // someCheckBox.setSelected(Preferences.userNodeForPackage(SecurityPrivacyPanel.class).getBoolean("someFlag", false));
        // or for org.openide.util with API spec. version >= 7.4:
        // someCheckBox.setSelected(NbPreferences.forModule(SecurityPrivacyPanel.class).getBoolean("someFlag", false));
        // or:
        // someTextField.setText(SomeSystemOption.getDefault().getSomeStringProperty());
        for(PasswordProvider provider : Lookup.getDefault().lookupAll(PasswordProvider.class))
        {
            provider.load();
        }         
    }

    void store() {
        // TODO store modified settings
        // Example:
        // Preferences.userNodeForPackage(SecurityPrivacyPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or for org.openide.util with API spec. version >= 7.4:
        // NbPreferences.forModule(SecurityPrivacyPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or:
        // SomeSystemOption.getDefault().setSomeStringProperty(someTextField.getText());
        for(PasswordProvider provider : Lookup.getDefault().lookupAll(PasswordProvider.class))
        {
            provider.store();
        }        
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    @Override
    public void stateChanged(ChangeEvent e) 
    {
        controller.changed();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
