/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/templateTopComponent637.java to edit this template
 */
package openpkm.core;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import java.util.SortedSet;
import java.util.TreeSet;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.SwingUtilities;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import openpkm.base.FilterTagsProvider;
import openpkm.base.TagsProvider;
import org.netbeans.api.project.Project;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.awt.UndoRedo;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Children;
import org.openide.nodes.Node;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.Utilities;
import org.openide.util.lookup.Lookups;
import org.openide.util.lookup.ProxyLookup;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//openpkm.core//Tags//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "TagsTopComponent",
        iconBase = "openpkm/core/resources/document_hash_tag.png",
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(mode = "properties", openAtStartup = true)
@ActionID(category = "Window", id = "openpkm.core.TagsTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_TagsAction",
        preferredID = "TagsTopComponent"
)
@Messages({
    "CTL_TagsAction=Tags",
    "CTL_TagsTopComponent=Tags Window",
    "HINT_TagsTopComponent=This is a Tags window"
})
public final class TagsTopComponent extends TopComponent implements ExplorerManager.Provider, ChangeListener
{
    private final ExplorerManager explorerManager = new ExplorerManager();
    private final UndoRedo.Manager undoRedoManager = new UndoRedo.Manager();  
    private final Tags tags = new Tags();
    
    private Lookup.Result<Project> result;    
    
    public TagsTopComponent() {
        initComponents();
        setName(Bundle.CTL_TagsTopComponent());
        setToolTipText(Bundle.HINT_TagsTopComponent());
        putClientProperty(TopComponent.PROP_DRAGGING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_MAXIMIZATION_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.TRUE);
        associateLookup(new ProxyLookup(ExplorerUtils.createLookup(explorerManager, getActionMap()), Lookups.singleton(this)));  
        explorerManager.setRootContext(new AbstractNode(tags));   
        result = Utilities.actionsGlobalContext().lookupResult(Project.class);          
    }
    
    private String getFilterTags(List<String> tags)
    {
        StringBuilder sb = new StringBuilder();
        for(String tag : tags)
        {
            sb.append(" #");
            sb.append(tag);
        }
        return sb.toString();
    }    
    
    @Override
    public ExplorerManager getExplorerManager() 
    {
        return explorerManager;
    }
    
    @Override
    public UndoRedo getUndoRedo() 
    {
        return undoRedoManager;
    }       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() 
    {
        // TODO add custom code on component opening
        
        FilterTagsProvider filterProvider = Lookup.getDefault().lookup(FilterTagsProvider.class);
        if(filterProvider != null)
        {
            filterProvider.addChangeListener(this);                    
        }        

        result.addLookupListener(tags);        
    }

    @Override
    public void componentClosed() 
    {
        // TODO add custom code on component closing
        
        FilterTagsProvider filterProvider = Lookup.getDefault().lookup(FilterTagsProvider.class);
        if(filterProvider != null)
        {
            filterProvider.removeChangeListener(this);                    
        } 
        
        result.removeLookupListener(tags);        
    }
    
    @Override
    public Action[] getActions() 
    {
        List<Action> actions = new ArrayList();
        for (Action action : super.getActions())
        {
            actions.add(action);
        }
        actions.add(new ClearFilterTagsAction());
        return actions.toArray(new Action[actions.size()]);
    }     

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
    
    @Override
    public void stateChanged(ChangeEvent e) 
    {
        List<String> tags = Lookup.getDefault().lookup(FilterTagsProvider.class).getFilterTags();
        if(tags.isEmpty())
        {
            setDisplayName("Tags");
        }
        else
        {
            setDisplayName("Tags" + getFilterTags(tags));
        }
    }    
    
    private final class Tags extends Children.Keys<String> implements LookupListener
    {
        private final List<TagsProvider> providers = new ArrayList();
                        
        @Override
        public void resultChanged(LookupEvent event) 
        { 
            Collection<Project> projects = (Collection<Project>) result.allInstances();
            if(!projects.isEmpty())
            {
                providers.clear();
                for(Project project : projects)
                {
                    providers.addAll(project.getLookup().lookupAll(TagsProvider.class));                    
                }
                updateKeys();                
            }
        }           
        
        @Override
        protected void addNotify() 
        {
            updateKeys();
        }
        
        public Collection<TagsProvider> getProviders()
        {
            if(providers != null)
            {
                return Collections.unmodifiableCollection(providers);
            }
            return Collections.EMPTY_LIST;
        }

        private void updateKeys() 
        {               
            SwingUtilities.invokeLater(() -> 
            {
                SortedSet<String> tags = new TreeSet<String>();  
                Iterator<TagsProvider> iterator = getProviders().iterator();
                while(iterator.hasNext())
                {
                    tags.addAll(iterator.next().getTags());  
                } 
                tags.remove("");
                setKeys(tags);  
            });  
        }

        @Override
        protected void removeNotify()
        {
            setKeys(Collections.<String>emptySet());
        }

        @Override
        protected Node[] createNodes(String tag) 
        {
            return new Node[] {new TagNode(tag)};
        }         
    }
    
    private static final class ClearFilterTagsAction extends AbstractAction
    {       
        public ClearFilterTagsAction() 
        {
            super("Remove All Tags from Filter");
        }        
        
        @Override
        public void actionPerformed(ActionEvent evt) 
        {
            FilterTagsProvider provider = Lookup.getDefault().lookup(FilterTagsProvider.class);
            provider.clearFilterTags();
        }        
    }     
}
