/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package openpkm.core;

import java.awt.EventQueue;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;
import java.util.SortedSet;
import java.util.StringJoiner;
import java.util.TreeSet;
import openpkm.base.KnowledgeGraphProvider;
import openpkm.base.Topic;
import openpkm.utils.TopicNode;
import org.openide.explorer.ExplorerManager;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Children;
import org.openide.nodes.Node;
import org.openide.util.Lookup;

/**
 *
 * @author rok
 */
public class TopicVisualPanel extends javax.swing.JPanel implements ExplorerManager.Provider
{
    private final ExplorerManager explorerManager = new ExplorerManager();     
    
    /**
     * Creates new form TopicVisualPanel
     */
    public TopicVisualPanel() {
        initComponents();
    }
    
    @Override
    public String getName() 
    {
        return "Topics";
    }  
    
    @Override
    public ExplorerManager getExplorerManager() 
    {
        return explorerManager;
    }  
    
    public void setTopics(Lookup.Provider provider)
    {
        assert provider != null;        
        KnowledgeGraphProvider knowledgeGraph = provider.getLookup().lookup(KnowledgeGraphProvider.class);
        if(knowledgeGraph != null)
        {
            TopicsChildren topics = new TopicsChildren(knowledgeGraph);
            explorerManager.setRootContext(new AbstractNode(topics));
        }        
    } 
    
    public void setSelectedTopics(Set<Topic> topics)
    {
        StringJoiner joiner = new StringJoiner(", ");
        for(Topic topic : topics)
        {
            joiner.add(topic.getName());
        }
        jLabel2.setText(joiner.toString());
    }
    
    public Set<Topic> getTopics()
    {
        Node[] nodes = explorerManager.getSelectedNodes();
        if(nodes.length > 0)
        {
            Set<Topic> topics = new HashSet<>();
            for(Node node : nodes)
            {
                Topic topic = node.getLookup().lookup(Topic.class);
                if(topic != null)
                {
                    topics.add(topic);
                }
            }
            return topics;
        }
        return null;
    }      
    
    static final class TopicsChildren extends Children.Keys<Topic> 
    {
        private final KnowledgeGraphProvider provider;

        public TopicsChildren(KnowledgeGraphProvider provider)
        {
            this.provider = provider;
        }  

        @Override
        protected void addNotify() 
        {
            updateKeys();                             
        }

        private void updateKeys() 
        {
            EventQueue.invokeLater(new Runnable() 
            {
                public void run()
                {                                                
                    SortedSet<Topic> topics = new TreeSet<Topic>(Topic.nameComparator());
                    topics.addAll(provider.getRootTopics());           
                    setKeys(topics);                   
                }
            });
        }        

        @Override
        protected void removeNotify() 
        {                            
            setKeys(Collections.<Topic>emptySet());
        }

        @Override
        protected Node[] createNodes(Topic topic) 
        {
            return new Node[] {new TopicNode(provider, topic)};
        }           
    }       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        iconView3 = new org.openide.explorer.view.IconView();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());
        add(iconView3, java.awt.BorderLayout.CENTER);

        jLabel2.setPreferredSize(new java.awt.Dimension(0, 16));
        add(jLabel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openide.explorer.view.IconView iconView3;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
