/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package openpkm.core;

import openpkm.base.TitleProvider;
import org.cef.browser.CefBrowser;

/**
 *
 * @author Rok Koren
 */
public class WatchLaterVisualPanel extends javax.swing.JPanel 
{ 
    private final TitleProvider provider;
    
    private CefBrowser browser;
    
    /**
     * Creates new form WatchLaterVisualPanel
     */
    public WatchLaterVisualPanel(TitleProvider provider) 
    {
        this.provider = provider;
        initComponents();      
    }
    
    @Override
    public String getName() 
    {
        return provider.getTitle();
    } 
    
    public CefBrowser getBrowser()
    {
        return browser;
    }

    public void setBrowser(CefBrowser browser)
    {
        this.browser = browser;
        add(browser.getUIComponent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
