/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/visualPanel.java to edit this template
 */
package openpkm.raindrop;

import java.awt.Component;
import java.beans.BeanInfo;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.ListCellRenderer;
import javax.swing.SwingConstants;
import openpkm.base.IconProvider;
import openpkm.base.TitleProvider;
import org.netbeans.api.project.Project;
import org.netbeans.api.project.ui.OpenProjects;
import org.openide.util.ImageUtilities;

public final class CreateRaindropVisualPanel1 extends JPanel 
{
    private final DefaultComboBoxModel<RaindropProject> projects = new DefaultComboBoxModel<>(); 
    
    private final ListCellRenderer renderer = new ListCellRendererImpl();
    
    /**
     * Creates new form CreateRaindropVisualPanel1
     */
    public CreateRaindropVisualPanel1() 
    {
        setProjects();
        initComponents();
    }

    @Override
    public String getName() {
        return "Step #1";
    }
    
    private void setProjects()
    {
        Project mainProject = OpenProjects.getDefault().getMainProject();
        Project[] openProjects = OpenProjects.getDefault().getOpenProjects();
        for(Project project : openProjects)
        {
            if(project instanceof RaindropProject raindropProject)
            {
                projects.addElement(raindropProject);
            }
        }
        if(mainProject instanceof RaindropProject raindropProject)
        {
            projects.setSelectedItem(raindropProject);                     
        }
    }
    
    private static class ListCellRendererImpl extends JLabel implements ListCellRenderer<RaindropProject>
    {        
        public ListCellRendererImpl() 
        {
            setOpaque(true);
            setHorizontalAlignment(SwingConstants.LEADING);
            setVerticalAlignment(CENTER);
            setIconTextGap(10);
        }        

        @Override
        public Component getListCellRendererComponent(JList list, RaindropProject raindropProject, int index, boolean isSelected, boolean cellHasFocus) 
        {
            if (isSelected) {
                setBackground(list.getSelectionBackground());
                setForeground(list.getSelectionForeground());
            } else {
                setBackground(list.getBackground());
                setForeground(list.getForeground());
            }

            if(raindropProject == null)
            {
                setText("");
                setIcon(null);
            }
            else
            {  
                TitleProvider titleProvider = raindropProject.getLookup().lookup(TitleProvider.class);
                if(titleProvider != null)
                {
                    setText(titleProvider.getTitle());                     
                }
                
                IconProvider iconProvider = raindropProject.getLookup().lookup(IconProvider.class);
                if(iconProvider != null)
                {
                    setIcon(ImageUtilities.image2Icon(iconProvider.getIcon(BeanInfo.ICON_COLOR_16x16)));                      
                }
            }
            
            return this;
        }
    }     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(CreateRaindropVisualPanel1.class, "CreateRaindropVisualPanel1.jLabel1.text") + ";"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(jLabel1, gridBagConstraints);

        jComboBox1.setModel(projects);
        jComboBox1.setRenderer(renderer);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        add(jComboBox1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<RaindropProject> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
