/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package openpkm.core.neo4j;

import java.awt.EventQueue;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;
import java.util.SortedSet;
import java.util.StringJoiner;
import java.util.TreeSet;
import openpkm.base.Goal;
import openpkm.base.GoalsGraphProvider;
import openpkm.utils.GoalNode;
import org.openide.explorer.ExplorerManager;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Children;
import org.openide.nodes.Node;
import org.openide.util.Lookup;

/**
 *
 * @author rok
 */
public class GoalVisualPanel extends javax.swing.JPanel implements ExplorerManager.Provider
{
    private final ExplorerManager explorerManager = new ExplorerManager();  
    
    /**
     * Creates new form GoalVisualPanel
     */
    public GoalVisualPanel() 
    {
        initComponents();
    }

    @Override
    public String getName() 
    {
        return "Goals";
    }  
    
    @Override
    public ExplorerManager getExplorerManager() 
    {
        return explorerManager;
    }      
    
    public void setGoals(Lookup.Provider provider)
    {
        assert provider != null;        
        GoalsGraphProvider goalsGraph = provider.getLookup().lookup(GoalsGraphProvider.class);
        if(goalsGraph != null)
        {
            GoalsChildren goals = new GoalsChildren(goalsGraph);
            explorerManager.setRootContext(new AbstractNode(goals));
        }        
    } 
    
    public void setSelectedGoals(Set<Goal> goals)
    {
        StringJoiner joiner = new StringJoiner(", ");
        for(Goal goal : goals)
        {
            joiner.add(goal.getName());
        }
        jLabel1.setText(joiner.toString());
    }
    
    public Set<Goal> getGoals()
    {
        Node[] nodes = explorerManager.getSelectedNodes();
        if(nodes.length > 0)
        {
            Set<Goal> goals = new HashSet<>();
            for(Node node : nodes)
            {
                Goal goal = node.getLookup().lookup(Goal.class);
                if(goal != null)
                {
                    goals.add(goal);
                }
            }
            return goals;
        }
        return null;
    }      
    
    static final class GoalsChildren extends Children.Keys<Goal> 
    {
        private final GoalsGraphProvider provider;

        public GoalsChildren(GoalsGraphProvider provider)
        {
            this.provider = provider;
        }  

        @Override
        protected void addNotify() 
        {
            updateKeys();                             
        }

        private void updateKeys() 
        {
            EventQueue.invokeLater(new Runnable() 
            {
                public void run()
                {                                                
                    SortedSet<Goal> goals = new TreeSet<Goal>(Goal.nameComparator());
                    goals.addAll(provider.getRootGoals());           
                    setKeys(goals);                   
                }
            });
        }        

        @Override
        protected void removeNotify() 
        {                            
            setKeys(Collections.<Goal>emptySet());
        }

        @Override
        protected Node[] createNodes(Goal goal) 
        {
            return new Node[] {new GoalNode(provider, goal)};
        }           
    }      
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        iconView1 = new org.openide.explorer.view.IconView();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setPreferredSize(new java.awt.Dimension(0, 16));
        add(jLabel1, java.awt.BorderLayout.PAGE_START);
        add(iconView1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openide.explorer.view.IconView iconView1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
