/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/templateTopComponent637.java to edit this template
 */
package openpkm.core.neo4j;

import java.awt.Image;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import java.util.SortedSet;
import java.util.TreeSet;
import javax.swing.SwingUtilities;
import openpkm.base.IconsProvider;
import openpkm.base.Thought;
import openpkm.base.ThoughtsProvider;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.awt.UndoRedo;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Children;
import org.openide.nodes.Node;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.Utilities;
import org.openide.util.lookup.Lookups;
import org.openide.util.lookup.ProxyLookup;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//openpkm.core.neo4j//Thoughts//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "ThoughtsTopComponent",
        iconBase = "openpkm/core/resources/comments.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "output", openAtStartup = true)
@ActionID(category = "Window", id = "openpkm.core.neo4j.ThoughtsTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_ThoughtsAction",
        preferredID = "ThoughtsTopComponent"
)
@Messages({
    "CTL_ThoughtsAction=Thoughts",
    "CTL_ThoughtsTopComponent=Thoughts Window",
    "HINT_ThoughtsTopComponent=This is a Thoughts window"
})
public final class ThoughtsTopComponent extends TopComponent implements ExplorerManager.Provider
{
    private final ExplorerManager explorerManager = new ExplorerManager();
    private final UndoRedo.Manager undoRedoManager = new UndoRedo.Manager();  
    private final Thoughts thoughts = new Thoughts();
    
    private Lookup.Result<ThoughtsProvider> result;   
    
    public ThoughtsTopComponent() {
        initComponents();
        setName(Bundle.CTL_ThoughtsTopComponent());
        setToolTipText(Bundle.HINT_ThoughtsTopComponent());
        putClientProperty(TopComponent.PROP_DRAGGING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_MAXIMIZATION_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_SLIDING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.TRUE);
        associateLookup(new ProxyLookup(ExplorerUtils.createLookup(explorerManager, getActionMap()), Lookups.singleton(this)));  
        explorerManager.setRootContext(new AbstractNode(thoughts));   
        result = Utilities.actionsGlobalContext().lookupResult(ThoughtsProvider.class);    
    }
    
    @Override
    public ExplorerManager getExplorerManager() 
    {
        return explorerManager;
    }
    
    @Override
    public UndoRedo getUndoRedo() 
    {
        return undoRedoManager;
    }       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listView1 = new org.openide.explorer.view.ListView();

        setLayout(new java.awt.BorderLayout());
        add(listView1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openide.explorer.view.ListView listView1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
        result.addLookupListener(thoughts);  
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
        result.removeLookupListener(thoughts); 
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
    
    private final class Thoughts extends Children.Keys<Thought> implements LookupListener
    {
        private List<ThoughtsProvider> providers;
                        
        @Override
        public void resultChanged(LookupEvent event) 
        { 
            Collection<ThoughtsProvider> coll = (Collection<ThoughtsProvider>) result.allInstances();
            if(!coll.isEmpty())
            {
                if(providers == null)
                {
                    providers = new ArrayList<>();
                }
                else
                {
                    providers.clear();                    
                }                                                          
                providers.addAll(coll);
                updateKeys();                
            }
        }           
        
        @Override
        protected void addNotify() 
        {
            updateKeys();
        }
        
        public Collection<ThoughtsProvider> getProviders()
        {
            if(providers != null)
            {
                return Collections.unmodifiableCollection(providers);
            }
            return Collections.EMPTY_LIST;
        }

        private void updateKeys() 
        {               
            SwingUtilities.invokeLater(() -> 
            {
                SortedSet<Thought> thoughts = new TreeSet<Thought>(Thought.textComparator());  
                Iterator<ThoughtsProvider> iterator = getProviders().iterator();
                while(iterator.hasNext())
                {
                    thoughts.addAll(iterator.next().getThoughts());  
                } 
                setKeys(thoughts);                                                  
            });  
        }

        @Override
        protected void removeNotify()
        {                   
            setKeys(Collections.<Thought>emptySet());
        }

        @Override
        protected Node[] createNodes(Thought thought) 
        {
            return new Node[] {new ThoughtNode(thought)};
        }         
    } 
    
    private static final class ThoughtNode extends AbstractNode
    {
        private final Thought thought;        
        
        public ThoughtNode(Thought thought) 
        {
            super(Children.LEAF, new ProxyLookup(Lookups.singleton(thought)));
            setName(thought.getThoughtID());
            setDisplayName(thought.getText());
            this.thought = thought;
        }   

        private Image getIcon(boolean opened) 
        {
            IconsProvider provider = Lookup.getDefault().lookup(IconsProvider.class);
            return provider.getImage(thought.getType().getIcon());        
        }

        @Override
        public Image getIcon(int type) 
        {
            return getIcon(false);
        }

        @Override
        public Image getOpenedIcon(int type) 
        {
            return getIcon(true);
        }          
    }
}
