/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package openpkm.core.neo4j;

import java.awt.EventQueue;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;
import java.util.SortedSet;
import java.util.StringJoiner;
import java.util.TreeSet;
import openpkm.base.Thought;
import openpkm.base.ThoughtsGraphProvider;
import org.openide.explorer.ExplorerManager;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Children;
import org.openide.nodes.Node;
import org.openide.util.Lookup;

/**
 *
 * @author rok
 */
public class ThoughtVisualPanel extends javax.swing.JPanel implements ExplorerManager.Provider
{
    private final ExplorerManager explorerManager = new ExplorerManager(); 
    
    /**
     * Creates new form ThoughtVisualPanel3
     */
    public ThoughtVisualPanel() 
    {
        initComponents();
    }
    
    @Override
    public String getName() 
    {
        return "Thoughts";
    }  

    @Override
    public ExplorerManager getExplorerManager() 
    {
        return explorerManager;
    }  
    
    public void setThoughts(Lookup.Provider provider)
    {
        assert provider != null;        
        ThoughtsGraphProvider thoughtsProvider = provider.getLookup().lookup(ThoughtsGraphProvider.class);
        if(thoughtsProvider != null)
        {
            ThoughtsChildren thoughts = new ThoughtsChildren(thoughtsProvider);
            explorerManager.setRootContext(new AbstractNode(thoughts));
        }        
    } 
    
    public void setSelectedThoughts(Set<Thought> thoughts)
    {
        StringJoiner joiner = new StringJoiner(", ");
        for(Thought thought : thoughts)
        {
            joiner.add(thought.getText());
        }
        jLabel1.setText(joiner.toString());
    }
    
    public Set<Thought> getThoughts()
    {
        Node[] nodes = explorerManager.getSelectedNodes();
        if(nodes.length > 0)
        {
            Set<Thought> thoughts = new HashSet<>();
            for(Node node : nodes)
            {
                Thought thought = node.getLookup().lookup(Thought.class);
                if(thought != null)
                {
                    thoughts.add(thought);
                }
            }
            return thoughts;
        }
        return null;
    }     
    
    static final class ThoughtsChildren extends Children.Keys<Thought> 
    {
        private final ThoughtsGraphProvider provider;

        public ThoughtsChildren(ThoughtsGraphProvider provider)
        {
            this.provider = provider;
        }  

        @Override
        protected void addNotify() 
        {
            updateKeys();                             
        }

        private void updateKeys() 
        {
            EventQueue.invokeLater(new Runnable() 
            {
                public void run()
                {                                                
                    SortedSet<Thought> thoughts = new TreeSet<Thought>(Thought.textComparator());
                    thoughts.addAll(provider.getRootThoughts());           
                    setKeys(thoughts);                   
                }
            });
        }        

        @Override
        protected void removeNotify() 
        {                            
            setKeys(Collections.<Thought>emptySet());
        }

        @Override
        protected Node[] createNodes(Thought thought) 
        {
            return new Node[] {new TreeOfThoughtsNode(provider, thought)};
        }           
    }     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        listView1 = new org.openide.explorer.view.ListView();

        setLayout(new java.awt.BorderLayout(0, 10));

        jLabel1.setPreferredSize(new java.awt.Dimension(0, 16));
        add(jLabel1, java.awt.BorderLayout.PAGE_START);
        add(listView1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private org.openide.explorer.view.ListView listView1;
    // End of variables declaration//GEN-END:variables
}
