/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/templateTopComponent637.java to edit this template
 */
package openpkm.core.neo4j;

import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import openpkm.base.ChangeSupportProvider;
import openpkm.base.Thought;
import openpkm.base.ThoughtsGraphProvider;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.awt.UndoRedo;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Children;
import org.openide.nodes.Node;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.Utilities;
import org.openide.util.lookup.Lookups;
import org.openide.util.lookup.ProxyLookup;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//openpkm.core.neo4j//TreeOfThoughts//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "TreeOfThoughtsTopComponent",
        iconBase = "openpkm/core/resources/tree_list.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "output", openAtStartup = true)
@ActionID(category = "Window", id = "openpkm.core.neo4j.TreeOfThoughtsTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_TreeOfThoughtsAction",
        preferredID = "TreeOfThoughtsTopComponent"
)
@Messages({
    "CTL_TreeOfThoughtsAction=Tree Of Thoughts",
    "CTL_TreeOfThoughtsTopComponent=Tree Of Thoughts Window",
    "HINT_TreeOfThoughtsTopComponent=This is a Tree Of Thoughts window"
})
public final class TreeOfThoughtsTopComponent extends TopComponent implements ExplorerManager.Provider, LookupListener
{
    private static final Logger LOG = Logger.getLogger(TreeOfThoughtsTopComponent.class.getName());  
    
    private final ExplorerManager explorerManager = new ExplorerManager();
    private final UndoRedo.Manager undoRedoManager = new UndoRedo.Manager();  
    private final Thoughts thoughts = new Thoughts();   
    
    private Lookup.Result<ThoughtsGraphProvider> result1;
    private Lookup.Result<Thought> result2;
    
    public TreeOfThoughtsTopComponent() 
    {
        initComponents();
        setName(Bundle.CTL_TreeOfThoughtsTopComponent());
        setToolTipText(Bundle.HINT_TreeOfThoughtsTopComponent());
        putClientProperty(TopComponent.PROP_MAXIMIZATION_DISABLED, Boolean.TRUE);
        associateLookup(new ProxyLookup(ExplorerUtils.createLookup(explorerManager, getActionMap()), Lookups.singleton(this)));  
        explorerManager.setRootContext(new AbstractNode(thoughts));   
        result1 = Utilities.actionsGlobalContext().lookupResult(ThoughtsGraphProvider.class);  
        result2 = Utilities.actionsGlobalContext().lookupResult(Thought.class); 
    }
    
    @Override
    public ExplorerManager getExplorerManager() 
    {
        return explorerManager;
    }
    
    @Override
    public UndoRedo getUndoRedo() 
    {
        return undoRedoManager;
    }     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        beanTreeView1 = new org.openide.explorer.view.BeanTreeView();

        setLayout(new java.awt.BorderLayout());

        beanTreeView1.setRootVisible(false);
        add(beanTreeView1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openide.explorer.view.BeanTreeView beanTreeView1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
        result1.addLookupListener(thoughts);  
        result2.addLookupListener(this);  
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
        result1.removeLookupListener(thoughts); 
        result2.removeLookupListener(this); 
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
    
    @Override
    public void resultChanged(LookupEvent event) 
    { 
        Collection<Thought> coll = (Collection<Thought>) result2.allInstances();
        if(!coll.isEmpty())
        {
            Node node = findPath(explorerManager.getRootContext(), coll.iterator().next());
            if(node != null)
            {
                Node[] nodes = {node};
                try
                {
                    explorerManager.setSelectedNodes(nodes);   
                    //beanTreeView1.expandNode(node);
                }
                catch(PropertyVetoException e)
                {
                    LOG.warning(e.getMessage());
                }
            }
        }
    }  

    private Node findPath(Node root, Thought target) 
    {
        Node node = root.getChildren().findChild(target.getThoughtID());
        if(node != null)
        {
            return node;
        }
        for(Node child : root.getChildren().getNodes())
        {
            node = findPath(child, target);
            if(node != null)
            {
                return node;
            }
        }
        return null;
    } 
    
    private final class Thoughts extends Children.Keys<ThoughtsGraphProvider> implements LookupListener, ChangeListener
    {
        private List<ThoughtsGraphProvider> providers;
                        
        @Override
        public void resultChanged(LookupEvent event) 
        { 
            Collection<ThoughtsGraphProvider> coll = (Collection<ThoughtsGraphProvider>) result1.allInstances();
            if(!coll.isEmpty())
            {
                if(providers == null)
                {
                    providers = new ArrayList<>();
                }
                else
                {
                    for(ThoughtsGraphProvider provider : providers)
                    {
                        if(provider instanceof ChangeSupportProvider csp)
                        {
                            csp.removeChangeListener(this);
                        }
                    }
                    providers.clear();                    
                }
                
                for (ThoughtsGraphProvider provider : coll) 
                {
                    if (provider instanceof ChangeSupportProvider csp) 
                    {
                        csp.addChangeListener(this);
                    }
                }                             
                
                providers.addAll(coll);
                updateKeys();                
            }
        }           
        
        @Override
        protected void addNotify() 
        {
            updateKeys();
        }
        
        public Collection<ThoughtsGraphProvider> getProviders()
        {
            if(providers != null)
            {
                return Collections.unmodifiableCollection(providers);
            }
            return Collections.EMPTY_LIST;
        }

        private void updateKeys() 
        {               
            SwingUtilities.invokeLater(() -> 
            {
                setKeys(getProviders());  
            });  
        }

        @Override
        protected void removeNotify()
        {
            for(ThoughtsGraphProvider provider : providers)
            {
                if(provider instanceof ChangeSupportProvider csp)
                {
                    csp.removeChangeListener(this);
                }
            }
            providers.clear();            
            
            setKeys(Collections.<ThoughtsGraphProvider>emptySet());
        }

        @Override
        protected Node[] createNodes(ThoughtsGraphProvider provider) 
        {
            List<Thought> thoughts = provider.getRootThoughts();
            Node[] nodes = new Node[thoughts.size()];
            
            for (int i = 0; i < thoughts.size(); i++) 
            {
                nodes[i] = new TreeOfThoughtsNode(provider, thoughts.get(i));
            }         
            
            return nodes;
        }  
        
        @Override
        public void stateChanged(ChangeEvent e) 
        {
            updateKeys();
        }         
    }     
}
