/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package openpkm.core.trello;

import java.awt.Color;

/**
 *
 * @author Rok Koren
 */
public class TrelloBoardVisualPanel2 extends javax.swing.JPanel {

    /**
     * Creates new form TrelloBoardVisualPanel2
     */
    public TrelloBoardVisualPanel2() {
        initComponents();
    }
    
    @Override
    public String getName() 
    {
        return "Background";
    }  
    
    public Color getBackgroundColor()
    {
        return jColorChooser1.getColor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
        add(jColorChooser1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JColorChooser jColorChooser1;
    // End of variables declaration//GEN-END:variables
}
