/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/templateTopComponent637.java to edit this template
 */
package openpkm.core.youtube;

import java.awt.BorderLayout;
import java.util.logging.Logger;
import javax.swing.event.ChangeListener;
import javax.swing.undo.CannotRedoException;
import javax.swing.undo.CannotUndoException;
import openpkm.base.LinkProvider;
import openpkm.jcef.CefAppProvider;
import org.cef.CefClient;
import org.cef.browser.CefBrowser;
import org.cef.browser.CefFrame;
import org.cef.handler.CefLoadHandler;
import org.cef.handler.CefLoadHandler.ErrorCode;
import org.cef.network.CefRequest;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.awt.UndoRedo;
import org.openide.util.ChangeSupport;
import org.openide.util.Lookup;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.lookup.Lookups;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//openpkm.core//YouTube//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "YouTubeTopComponent",
        iconBase = "openpkm/core/resources/youtube_video.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "openpkm.core.youtube.YouTubeTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_YouTubeAction",
        preferredID = "YouTubeTopComponent"
)
@Messages({
    "CTL_YouTubeAction=YouTube",
    "CTL_YouTubeTopComponent=YouTube Window",
    "HINT_YouTubeTopComponent=This is a YouTube window"
})
public final class YouTubeTopComponent extends TopComponent implements LinkProvider, UndoRedo, CefLoadHandler
{
    public static final String YOUTUBE_URL = "https://www.youtube.com";
    
    private static final Logger LOG = Logger.getLogger(YouTubeTopComponent.class.getName());     
    
    private CefClient client;    
    private CefBrowser browser; 
    
    private final ChangeSupport changeSupport = new ChangeSupport(this);    
    
    public YouTubeTopComponent() 
    {
        initComponents();
        setName(Bundle.CTL_YouTubeTopComponent());
        setToolTipText(Bundle.HINT_YouTubeTopComponent());

        CefAppProvider provider = Lookup.getDefault().lookup(CefAppProvider.class);
        if(provider != null)
        {
            try
            {                
                client = provider.getApp().createClient();
                browser = client.createBrowser(YOUTUBE_URL, false, false);                 
                
                add(browser.getUIComponent(), BorderLayout.CENTER);
            }
            catch(Exception e)
            {
                LOG.warning(e.getMessage());
            }
        }         
    }
    
    @Override
    public Lookup getLookup()
    {
        return Lookups.singleton(this);
    }
    
    @Override
    public UndoRedo getUndoRedo()
    {
        return this;
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        client.addLoadHandler(this);
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
        client.removeLoadHandler();
        if(browser != null)
        {
            browser.close(false);
        }        
        //client.dispose();       
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public String getLink() 
    {
        return browser.getURL();
    }
    
    @Override
    public void onLoadingStateChange(CefBrowser cb, boolean bln, boolean bln1, boolean bln2) 
    {
        changeSupport.fireChange();        
    }

    @Override
    public void onLoadStart(CefBrowser cb, CefFrame cf, CefRequest.TransitionType tt) 
    {
        
    }

    @Override
    public void onLoadEnd(CefBrowser cb, CefFrame cf, int i) 
    {
        changeSupport.fireChange(); 
    }

    @Override
    public void onLoadError(CefBrowser cb, CefFrame cf, ErrorCode ec, String string, String string1) 
    {
    }

    @Override
    public boolean canUndo() {
        return browser.canGoBack();
    }

    @Override
    public void undo() throws CannotUndoException {
        browser.goBack();
    }

    @Override
    public boolean canRedo() {
        return browser.canGoForward();
    }

    @Override
    public void redo() throws CannotRedoException {
        browser.goForward();
    }

    @Override
    public void addChangeListener(ChangeListener cl) 
    {
        changeSupport.addChangeListener(cl);
    }

    @Override
    public void removeChangeListener(ChangeListener cl) {
        changeSupport.removeChangeListener(cl);
    }

    @Override
    public String getUndoPresentationName() 
    {
        return "Back";
    }

    @Override
    public String getRedoPresentationName() 
    {
        return "Forward";
    }
}
