/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package openpkm.youtube;

import java.util.Arrays;
import javax.swing.DefaultComboBoxModel;
import openpkm.base.Video;
import openpkm.youtube.YouTubeDownloadWizardPanel.DownloadType;

/**
 *
 * @author Rok Koren
 */
public class YouTubeDownloadVisualPanel extends javax.swing.JPanel 
{    
    private final DefaultComboBoxModel<DownloadType> types = new DefaultComboBoxModel<>();     
    private final DefaultComboBoxModel<Video.Resolution> resolutions = new DefaultComboBoxModel<>();     
    
    /**
     * Creates new form YouTubeDownloadVisualPanel
     */
    public YouTubeDownloadVisualPanel() 
    {
        setTypes();
        setResolutions();        
        initComponents();
    }
    
    @Override
    public String getName() 
    {
        return "Download";
    }  

    private void setTypes()
    {
        types.removeAllElements();
        types.addAll(Arrays.asList(DownloadType.values()));        
    }   
    
    private void setResolutions()
    {
        resolutions.removeAllElements();
        resolutions.addAll(Arrays.asList(Video.Resolution.values()));        
    }       
    
    public DownloadType getDownloadType()
    {
        return (DownloadType)jComboBox1.getSelectedItem();
    }
    
    public Video.Resolution getDownloadResolution()
    {
        return (Video.Resolution)jComboBox2.getSelectedItem();
    }  
    
    public boolean isDownloadSubtitles()
    {
        return jCheckBox1.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jCheckBox1 = new javax.swing.JCheckBox();

        setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(YouTubeDownloadVisualPanel.class, "YouTubeDownloadVisualPanel.jLabel1.text") + ":"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(jLabel1, gridBagConstraints);

        jComboBox1.setModel(types);
        jComboBox1.setSelectedItem(DownloadType.NONE);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                download(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jComboBox1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        add(filler1, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(YouTubeDownloadVisualPanel.class, "YouTubeDownloadVisualPanel.jLabel2.text") + ":"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(jLabel2, gridBagConstraints);

        jComboBox2.setModel(resolutions);
        jComboBox2.setSelectedItem(Video.Resolution.LOWEST);
        jComboBox2.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jComboBox2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        add(filler2, gridBagConstraints);

        jCheckBox1.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox1, org.openide.util.NbBundle.getMessage(YouTubeDownloadVisualPanel.class, "YouTubeDownloadVisualPanel.jCheckBox1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        add(jCheckBox1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void download(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_download
        boolean isDownload = getDownloadType() != DownloadType.NONE;
        jComboBox2.setEnabled(isDownload);
    }//GEN-LAST:event_download


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<DownloadType> jComboBox1;
    private javax.swing.JComboBox<Video.Resolution> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
